### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by TDSrock** [ebullient/ttrpg-convert-cli#181]
I am a little bit annoyed that I am failing to find any documentation on the data map that is supported in each template type.

I'm running into this issue due to me trying to add a simple bit of data to my templates (all of them) which I would ideally be something akin to:
```
source: {resource.source}
```
OR
```
source:
    book: {resource.source.book}
    page: {resource.source.page}
```
(And in some cases things have several sources so a for loop or some other mechanism to have each of these version within the same space, would be nice to have)
but now it prints the full book name + the page number. I would just like to break that information out so I can use other obsidian features to help sort things.

I initially assumed I should look at the JSON data, as in the source I couldn't find anything that builds this combined data. When I looked into the JSON data the page numbers are split away from the books within the sourcing information...

Or am I doing something silly/misunderstanding?

**Comment by ebullient** [comment]
I do track sources (where there are several). I don't currently expose those for you to use in templates. Not because I can't, but because no one has asked for it. 

If you're making a request to have book/page references accessible for templates, we can start there. Remember I do this in my spare time. It is a lot, it can be fussy, and I prioritized making functional content that renders well and is readable over making extensive documentation for something that is somewhat fluid. Where there are variations in how things are rendered, I try to provide an example with the alternate usage.

**Comment by ebullient** [comment]
I'm happy to take PRs for contributions to the examples directory. ;)

Getting source/page pairs out is involved, I'm working on it. In general, things happen in stages:

1. EVERYTHING is "parsed". Directories are scanned, json files are loosely parsed, with known top-level types indexed. If you run the CLI with the `--index` option, you can see the keys for all discovered and/or constructed nodes, and a second index for the smaller set that has been "allowed". Filtering can happen because the source was excluded, or because one node (say, a beastie), was marked as a reprint of another, that is already included. I think the full index also contains a map of keys to their replacement (the node that should be used instead). The list of sources 

2. A second phase converts the included nodes into notes. This is when the contents of each node are parsed in detail, recursively. There is roughly one Java class per emitted type that does the conversion (`Json2*`). The result is attached to one of the classes in the qute package (`Qute*`). I don't do full getters/setters here. Any public field is implicitly available directly to a template (`resource.fieldName`). Any getter on a `Qute*` object is also available to the template in the usual Java bean conversion sense: `getData()` would be available as `resource.data`. In some cases, I have additional inner classes that provide a toString() method. You can then either reference the field itself (which will implicitly call the toString() method), or you could reference the inner fields.


Note: I did the 5e side first, and improved some things when I started the pf2e work, so the two sides are not exactly the same, I'm reconciling things as I go to bring them closer together.

**Comment by TDSrock** [comment]
> I have an idea. Give me a bit.

If you would like we could link up over the weekend to see how collaboration is best achieved. Note that I am not too familiar with Java. I'm mainly over in C, C++, and C#. (also some TypeScript when i did web-dev)

**Comment by ebullient** [comment]
I have a doclet.. and now a lot of fixups. ;)
