### ISSUE TITLE
🐛 Machine does not support CPU features

### ISSUE THREAD

**Issue by theEmpirator** [ebullient/ttrpg-convert-cli#295]
Hello, I have had the following issue when trying to run the ttrpg-convert.exe from the command line with the following command:
`ttrpg-convert.exe --index -o dm 5etools-mirror-1.github.io/data`

"The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option."

I do not quite understand what is going on, I have just started getting into the stuff.  Is my computer too old? I tried changing the -march option to `-march = native` or `-march = compatibility` but to no avail.

## Configuration
- **OS**: Windows 10
- **CLI version**: v.1.196.0
- **CLI type**: don't know what this means

Has anybody encountered the same problem? I am trying to get 5etools to my Obsidian using this guide: https://obsidianttrpgtutorials.com/Obsidian+TTRPG+Tutorials/Plugin+Tutorials/TTRPG-Convert-CLI/TTRPG-Convert-CLI+5e

Thanks for any help!

**Comment by ebullient** [comment]
CLI type: you're using a native binary (the exe) instead of JBang (the Jar)

I think we've seen this before, and it was an older computer, which means the jar form may work better.

Can you be more specific about which version of Win 10? Windows 10 22H2, Windows 10 21H2 .. ?

**Comment by theEmpirator** [comment]
Thanks! My version is Windows 10 Pro, Version 10.0.19045

For the jar form I would need Java to open and run it, right?

**Comment by ebullient** [comment]
That's right.

If you're familiar with Java, that is absolutely one path to go down.
If you aren't, JBang can help.

This is referenced from the [README](https://github.com/ebullient/ttrpg-convert-cli/blob/main/README.md#install-the-ttrpg-convert-cli): https://github.com/ebullient/ttrpg-convert-cli/blob/main/docs/usage/alternateRun.md

Sounds like we need some additional data in [README-WINDOWS.md](https://github.com/ebullient/ttrpg-convert-cli/blob/main/README-WINDOWS.md) and possibly in Josh's tutorial to answer the "what happens if I get this message" question. Both of us will take suggestions for words and instructions that would have helped you find your way. I don't use Windows, so I need help with useful explanations.

**Comment by theEmpirator** [comment]
I tried it with the Java one (was confused at first because I did not understand that Eclipse Temurin was Java, I thought the link had misdirected me) and it worked! Consider me amazed 😄 I think my computer is exceptionally old (10 years), so this problem might not occur for many people.

The documentation is actually pretty great, especially for noob users like me. The step-by-step instructions are very useful. The only difficult thing is sometimes finding where the instructions are, especially if one is new to github folder structures (For example, I have found the README when scrolling down on the main page of the project, but apparently there is some additional documentation inside the docs folder.) But I guess the typical target audience knows more about programming/command line stuff anyway.

Thank you so much for the help and thanks for all the work you put into this project!
