### ISSUE TITLE
Plane Shift source map not working

### ISSUE THREAD

**Issue by VCDragoon** [ebullient/ttrpg-convert-cli#320]
The Plane Shift source mapping abbreviations to 5e.Tools aren't working as expected.

This was encountered using the CLI with a config file, where the Plane Shift books included in the "full-source"/"books" array in the JSON.

Correctly importing the files.

The CLI threw the error: ` Unable to read source file at path D:\DND Backups\07 - CLI\5eTools\bin\5etools-mirror-1.github.io\data\book\book-psa.json (D:\DND Backups\07 - CLI\5eTools\bin\5etools-mirror-1.github.io\data\book\book-psa.json)`

## Configuration

- **OS**: Windows
- **CLI version**: 2.2.17
- **CLI type**: native command

**Sources**:
All Plane Shift sources.

**Comment by VCDragoon** [comment]
Should hopefully be fixed by #321

**Comment by ebullient** [comment]
What you didn't show (when opening this item) is what your command and config look like. 

The problem here isn't the source, it's the switch from the source to the id that 5etools is using, they broke expected convention. For example, in books.json: 

```
  "id": "PS-Z",
  "source": "PSZ",
```

In most cases, the source id is what we use (so changing that source id would be a bad plan, as it would break all of the other references to those types).

I need to fix the lookup. It's an atypical source to id conversion that I'm not accounting for.
