### ISSUE TITLE
✨ Allow for more different file naming conventions

### ISSUE THREAD

**Issue by Pachtjuilaard** [ebullient/ttrpg-convert-cli#329]
**Describe the solution you'd like**
Currently, all file names are being slugified for compatibility. When that wouldn't be an issue, it could be nice if there's a setting to set the file names in Title Case instead, with the sources in UPPERCASE and between parentheses. Some exceptions need to be made for file names with /, \ or : in the title of course.  

**Describe alternatives you've considered**
I've been working on a Templater script that changes all file names into title case, but it's quite slow and buggy still.

**Comment by ebullient** [comment]
If you change the file names, it makes it more expensive to edit and re-run later (and believe me, you'll want to re-run later). We don't recommend it. Is this a file navigation issue, or a "how this renders in dataview" issue? 

Every file name has an alias, use it. You can make dataview queries (as an example) put the first alias in a column instead of the file name.

**Comment by Pachtjuilaard** [comment]
For me it's more of a usability and readability issue. I use Obsidian as a DM and as a player, and I'm taking lots of notes. The slugified file names still show up in the file explorer and when making links, and I'd love to be able to link to spells, feats, etc, by simply typing in the name of the ability, without having to write out an alias for every link I create. I also think it could be more user friendly for people using the same vault, who are not as used to using Obsidian.

**Comment by ebullient** [comment]
You should be able to type the alias, and obsidian should auto-complete the rest..

**Comment by ebullient** [comment]
I am going to close this, as I know that Obsidian autocompletes both wikilinks and markdown links with aliases. You should never have to actually type out the whole link with the alias. Just type the Alias, and let Obsidian do the rest.

I understand that lower-kebab-case is not the favorite, but it is consistent across all platforms (whether those file systems are case sensitive or not) and behaves predictably.

There is at least one file explorer plugin that will show the first alias instead of the file name, or you could take the other direction and use the Folder Notes plugin to prevent those folders from opening.. so that when you click on them, you get the folder note with the index full of names instead.
